name: CI-windows-build

on: push

jobs:
  windows-msvc-build:

    runs-on: ${{matrix.run-machine}}
    
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        compiler: [msvc-2017, msvc-2019]
        base-flags: ["", -DJINJA2CPP_CXX_STANDARD=17]
        build-config: [Release, Debug]
        build-platform: [x86, x64]
        build-runtime: ["", /MT, MD]

        include:
          - compiler: msvc-2017
            build-platform: x86
            run-machine: windows-2016
            generator: Visual Studio 15 2017
          - compiler: msvc-2017
            build-platform: x64
            run-machine: windows-2016
            generator: Visual Studio 15 2017 Win64
          - compiler: msvc-2019
            build-platform: x86
            run-machine: windows-2019
            generator: Visual Studio 16 2019
          - compiler: msvc-2019
            build-platform: x64
            run-machine: windows-2019
            generator: Visual Studio 16 2019 Win64
        
    
    steps:
    - uses: actions/checkout@v1

    - name: Build
      env:
        INPUT_COMPILER: ${{ matrix.compiler }}
        INPUT_BASE_FLAGS: ${{ matrix.base-flags }}
        INPUT_BUILD_CONFIG: ${{ matrix.build-config }}
        INPUT_EXTRA_FLAGS: ${{ matrix.extra-flags }}
        INPUT_BUILD_PLATFORM: ${{ matrix.build-platform }}
        INPUT_BUILD_RUNTIME: ${{ matrix.build-runtime }}
        INPUT_GENERATOR: ${{ matrix.generator }}
      run: |
        mkdir -p .build && cd .build
        cmake .. -G "%INPUT_GENERATOR%" -DCMAKE_BUILD_TYPE=%INPUT_BUILD_CONFIG% -DJINJA2CPP_MSVC_RUNTIME_TYPE=%INPUT_BUILD_RUNTIME% -DJINJA2CPP_DEPS_MODE=external-boost %INPUT_BASE_FLAGS% %INPUT_EXTRA_FLAGS%
        cmake --build . --target all --config Release

    - name: Test
      run: |
        mkdir -p .build && cd .build
        ctest -C Release -V
